# <VirtualHost *:80>
#     ServerName localhost

#     ProxyPreserveHost On
#     ProxyPass "/geoserver" "http://localhost:8080/geoserver"
#     ProxyPassReverse "/geoserver" "http://localhost:8080/geoserver"

#     DocumentRoot /var/www/html
#     <Directory /var/www/html>
#         AllowOverride All
#         Require all granted
#     </Directory>

#     # Logging
#     ErrorLog /var/log/apache2/error.log
#     CustomLog /var/log/apache2/access.log combined
# </VirtualHost>

<VirtualHost *:443>
    ServerName lmsdev.dalmiabharat.com
    #ServerAlias lmsdev.dalmiabharat.com 

    # Proxy Pass Configuration
    ProxyPreserveHost On
    ProxyPass "/geoserver" "http://localhost:8080/geoserver"
    ProxyPassReverse "/geoserver" "http://localhost:8080/geoserver"
 
    # SSL Configuration
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/dalmia.pem
    # SSLCertificateKeyFile /var/www/html/ssl/Dalmiabharat2023-2024.key 
    # SSLCertificateChainFile /var/www/html/ssl/Dalmiabharat2023-2024.ca-bundle 

    # Document Root Configuration
    DocumentRoot "/var/www/html"
    <Directory "/var/www/html"> 
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted 
    </Directory>

    # Logging
    ErrorLog /var/log/apache2/error.log
    CustomLog /var/log/apache2/access.log combined
</VirtualHost>

